name: Ruby Gem

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Check if version.rb has changed
      id: version_check
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^lib/coaster/version.rb$"; then
          echo "VERSION_CHANGED=true" >> $GITHUB_ENV
        else
          echo "VERSION_CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Publish to GPR
      if: env.VERSION_CHANGED == 'true'
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/frograms *.gem
    - name: Publish to RubyGems
      if: env.VERSION_CHANGED == 'true'
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
